engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
ratings:
  paths:
    - "tslearn_addons/"
exclude_paths:
- "tslearn_addons/**.c"
- "tslearn_addons/docs/**"
